services:
  app: 
    build:
      context: app
    ports:
      - 5002:5002
    volumes:
      - ./app:/app
  pytorch_testing:
    build:
      context: pytorch_testing
    volumes:
      - ./pytorch_testing:/pytorch_testing
