services:
  backend: 
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 5002:5002
    volumes:
      - ./backend:/backend
  frontend: 
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./frontend
